### ISSUE TITLE
Serialized Output of Dashboard Options Inquiry

### ISSUE THREAD

**Issue by jpellman** [artefactual-labs/archivematica-acceptance-tests#31]
Hello,

As part of the feature testing, we'd like to save settings that we have toggled on and off in the dashboard to ensure reproducibility between our environment and the test environments we're setting up.  This would be to ensure that we're running the same pipeline that we would normally run on our data in prod.

The documentation under [Processing Configuration](https://www.archivematica.org/fr/docs/archivematica-1.6/user-manual/administer/dashboard-admin/#processing-configuration) indicates that these dashboard settings should be defined in a file named _processingMCP.xml_ (whose file name is configurable in the [MCPServer config file](https://wiki.archivematica.org/MCPServer#Config_File)).

I was unable to find _processingMCP.xml_ on our current prod server.  The filename assigned to the _processingXMLFile_ field under _MCPServer_ in the MCPServer config does not seem to have been changed from the default so if the config were written out somewhere based on the value of this parameter it should be where it would normally be in a stock Archivematica installation.  

There is a file located within the directory assigned to the _sharedDirectoryMounted_ in the MCPClient config that looks similar to what _processingMCP.xml_ should look like- this file is found at _./sharedMicroServiceTasksConfigs/processingMCPConfigs/defaultProcessingMCP.xml_ under directory defined by _sharedDirectoryMounted_.  The chief difference between this file and what we'd expect from _processingMCP.xml_, however, is that whereas we'd expect _processingMCP.xml_ to use prose-based names for the _applies_ and _goToChain_ fields (like [here](https://raw.githubusercontent.com/artefactual/archivematica-sampledata/master/TestTransfers/NoExtensionsImages/processingMCP.xml)), instead it populates these fields with UUIDs.

This leads to the following questions on our end:
* Is _defaultProcessingMCP.xml_ the correct file we'd want to use to ensure our pipeline settings are preserved on the test hosts?
* Are the UUIDs assigned to the microservices on our prod host (and used within the XML config) portable across hosts?  Can we drop in _defaultProcessingMCP.xml_ on the test hosts and have it work without any further configuration/tweaking?

**Comment by jrwdunham** [comment]
Hi @jpellman. Did you ever figure this out?

When you go to the administration/processing/ page and click the "Edit" button on the "default" row, you are editing the file called defaultProcessingMCP.xml, which should be at the location you describe in your last paragraph above. (On my local deploy, it is at /var/archivematica/sharedDirectory/sharedMicroServiceTasksConfigs/processingMCPConfigs/defaultProcessingMCP.xml.)

Every time AM creates a new transfer, it places a copy of that defaultProcessingMCP.xml into the root directory of the transfer. See the "Include default Transfer processingMCP.xml". (Note it uses the `no-clobber -n` option of `cp` so if you already have a processingMCP.xml file in the transfer it will NOT be overwritten.

So, yes, the file at sharedMicroServiceTasksConfigs/processingMCPConfigs/defaultProcessingMCP.xml is the one you want to use and, yes, that file should be portable across hosts. (In rare cases it may not be portable across versions of Archivematica because the workflow may change and micro-service chain links may be replaced by others with different UUIDs.)

**Comment by jpellman** [comment]
Hi @jrwdunham ,

Thanks for the clarification.  I think we've got it.
