### ISSUE TITLE
Distinguish process METS and output METS in the performance-stdout-no-write feature

### ISSUE THREAD

**Issue by barmintor** [artefactual-labs/archivematica-acceptance-tests#53]
in core/performance-stdout-no-write.feature (WIP)

the AIP output METS should be identical between instance A and instance B, but the process METS would be smaller.

**Comment by jrwdunham** [comment]
@barmintor can you explain what you mean by the distinction between "process" and "output" METS?

@barmintor @jhsimpson I just discovered that the disable capture output configuration that has been added to Archivematica branch dev/1.8.x (commit 41d4f9fc29266e7b8aca8576c83e3c028f084384) actually does not decrease the length of the METS file contained in an Archivematica AIP. When we stop passing output streams from MCPClient workers to the MCPServer, the result is that the `Tasks` table will contain empty strings for its stdout and stderr fields. However, the content of the METS file is determined by what is in the `Events` table and this table gets populated by the client scripts themselves (e.g., identifyFileFormat, normalize, etc.)

My question is whether we want to modify the client scripts to use the `CAPTURE_CLIENT_SCRIPT_OUTPUT` setting (or some other config setting) in order to decide whether to write output streams to the `Events` table. This would definitely reduce the size of the final METS file and may result in some processing time reduction.

**Comment by jrwdunham** [comment]
A good deal of analysis has already gone into investigating how the METS file can be reduced in size for scalability/performance improvements. See https://wiki.archivematica.org/PREMIS/METS_for_scalability and the internal https://jiscdev.atlassian.net/wiki/spaces/RDSSAR/pages/301859154/Optimising+how+we+write+METS+files.
